'use client';
import {Stage,Layer,Group,Rect,Ellipse,Shape,Image as KImage,Text,Transformer} from 'react-konva';
import {useEffect,useRef,useState} from 'react';
import Konva from 'konva';
import {Item,Page,W,H,effectState,make,moveOffset} from './model';
import {visual} from './effects';
import {drawText} from './text-render';
import {mediaUrl} from './files';
export type {Item} from './model';
type Props={page:Page;selection:string[];onSelect:(id:string|null,toggle?:boolean)=>void;onBatch:(patch:Record<string,Partial<Item>>)=>void;onMarquee:(ids:string[])=>void;scale:number;guide:boolean;grid:boolean;snap:boolean;time:number;playing:boolean;preview?:boolean;transparentPreview?:boolean;onEdit?:(id:string)=>void;onCreate?:(x:number,y:number)=>void;onExporter?:(fn:()=>string)=>void};
function MediaImage({item,time,playing,stage}:{item:Item;time:number;playing:boolean;stage:React.RefObject<Konva.Stage|null>}){const [source,setSource]=useState<HTMLImageElement|HTMLVideoElement>();useEffect(()=>{if(item.type==='video'){const v=document.createElement('video');v.src=mediaUrl(item.src);v.muted=true;v.playsInline=true;v.preload='auto';v.onloadeddata=()=>setSource(v);v.onerror=()=>setSource(undefined);v.load();return()=>{v.pause();v.removeAttribute('src');v.load()}}const i=new window.Image();i.onload=()=>setSource(i);i.src=mediaUrl(item.src)},[item.src,item.type]);useEffect(()=>{if(!(source instanceof HTMLVideoElement))return;const active=time>=item.start&&time<=item.start+item.duration;const target=Math.max(0,time-item.start+item.trim);const desired=item.mediaLoop&&source.duration?target%source.duration:Math.min(target,Math.max(0,(source.duration||target)-.02));if(Math.abs(source.currentTime-desired)>(playing?.2:.03))source.currentTime=desired;if(playing&&active)source.play().catch(()=>{});else source.pause()},[source,time,playing,item.start,item.duration,item.trim,item.mediaLoop]);return <KImage image={source} width={item.w} height={item.h} listening={false}/>}
export default function EditorCanvas(p:Props){const stage=useRef<Konva.Stage>(null),tr=useRef<Konva.Transformer>(null),drag=useRef<Record<string,{x:number;y:number}>>({}),dragCache=useRef<{nodes:[string,Konva.Node][];tx:number[];ty:number[]}>({nodes:[],tx:[],ty:[]}),marqueeStart=useRef<{x:number;y:number}|null>(null);const [box,setBox]=useState<{x:number;y:number;w:number;h:number}|null>(null),[tick,setTick]=useState(0);const needTick=!p.playing&&p.page.items.some(i=>i.type==='clock'||i.type==='timer');useEffect(()=>{if(!needTick)return;const id=setInterval(()=>setTick(t=>t+1),1000);return()=>clearInterval(id)},[needTick]);void tick;
useEffect(()=>{tr.current?.nodes(p.preview||p.playing?[]:p.selection.map(id=>stage.current?.findOne('#'+id)).filter((n):n is Konva.Node=>!!n&&!p.page.items.find(i=>i.id===n.id())?.locked&&!p.page.items.find(i=>i.id===n.id())?.fixed));tr.current?.getLayer()?.batchDraw()},[p.selection,p.page.items,p.playing,p.preview]);
useEffect(()=>{p.onExporter?.(()=>{const s=stage.current!;const copy=s.clone({container:document.createElement('div'),width:W,height:H,scaleX:1,scaleY:1});copy.find('Transformer').forEach(n=>n.destroy());copy.find('.guide').forEach(n=>n.destroy());copy.draw();const url=copy.toDataURL({pixelRatio:1});copy.destroy();return url})},[p.onExporter]);
const pageItem=make('rect',{...p.page.options,x:0,y:0,w:W,h:H,start:0,duration:p.page.duration,effect:p.page.effect,outEffect:p.page.outEffect,inDuration:p.page.inDuration,outDuration:p.page.outDuration});const pv=p.playing||p.preview?visual(pageItem,p.time,'Still',p.page.duration):{opacity:1,x:0,y:0,scaleX:1,scaleY:1,rotation:0,clip:undefined};
const pointer=()=>{const q=stage.current?.getPointerPosition();return q?{x:q.x/p.scale,y:q.y/p.scale}:null};
const select=(item:Item,e:any)=>{if(p.preview||p.playing||item.locked)return;if(e.evt.detail===2&&['text','clock','timer'].includes(item.type)){p.onSelect(item.id);p.onEdit?.(item.id);return}if(!p.selection.includes(item.id)||e.evt.shiftKey||e.evt.ctrlKey||e.evt.metaKey)p.onSelect(item.id,e.evt.shiftKey||e.evt.ctrlKey||e.evt.metaKey)};
return <Stage ref={stage} width={W*p.scale} height={H*p.scale} scaleX={p.scale} scaleY={p.scale} onMouseDown={e=>{if(p.preview||p.playing)return;if(e.target===e.target.getStage()||e.target.id()==='bg'){const q=pointer();if(!q)return;p.onSelect(null);marqueeStart.current=q;setBox({x:q.x,y:q.y,w:0,h:0})}}} onMouseMove={()=>{if(!marqueeStart.current)return;const q=pointer(),a=marqueeStart.current;if(q)setBox({x:Math.min(q.x,a.x),y:Math.min(q.y,a.y),w:Math.abs(q.x-a.x),h:Math.abs(q.y-a.y)})}} onMouseUp={()=>{if(box&&box.w>5&&box.h>5){const ids=p.page.items.filter(i=>!i.locked&&!i.hidden&&i.type!=='audio'&&i.x<box.x+box.w&&i.x+i.w>box.x&&i.y<box.y+box.h&&i.y+i.h>box.y).map(i=>i.id);p.onMarquee(ids)}else if(marqueeStart.current)p.onCreate?.(marqueeStart.current.x,marqueeStart.current.y);marqueeStart.current=null;setBox(null)}}><Layer><Rect id="bg" width={W} height={H} fill={p.page.bg==='transparent'?(p.preview&&!p.transparentPreview?'#000':'#00000000'):p.page.bg}/>{p.grid&&!p.preview&&<Shape name="guide" listening={false} sceneFunc={ctx=>{const c=(ctx as any)._context as CanvasRenderingContext2D;c.fillStyle='#ffffff20';for(let i=0;i<97;i++)c.fillRect(i*20,0,1,H);for(let i=0;i<55;i++)c.fillRect(0,i*20,W,1)}}/>}
<Group x={pv.x} y={pv.y} scaleX={pv.scaleX} scaleY={pv.scaleY} rotation={pv.rotation} opacity={pv.opacity} clipFunc={pv.clip}>{p.page.items.filter(i=>!i.hidden&&i.type!=='audio').map(item=>{const state=effectState(item,p.time,p.page.mode,p.page.duration);const run=p.playing||p.preview;let opacity=item.opacity,x=item.x,y=item.y,sx=1,sy=1;let clip:((c:Konva.Context)=>void)|undefined;
let angle=0;let fold:ReturnType<typeof visual>['fold'];if(run){if(!state.active)return null;const v=visual(item,p.time,p.page.mode,p.page.duration);const mo=moveOffset(item,p.time);opacity*=v.opacity;x+=v.x+mo.x;y+=v.y+mo.y;sx=v.scaleX;sy=v.scaleY;angle=v.rotation;clip=v.clip;fold=v.fold}
const common={id:item.id,x,y,width:item.w,height:item.h,rotation:item.rotation+angle,opacity,scaleX:sx,scaleY:sy,draggable:!run&&!item.locked&&!item.fixed,clipFunc:clip,onMouseDown:(e:any)=>select(item,e),onTap:(e:any)=>select(item,e),onDblClick:()=>{if(!item.locked&&!run){p.onSelect(item.id);p.onEdit?.(item.id)}},onDragStart:()=>{let ids=p.selection.includes(item.id)?p.selection:[item.id];if(item.groupId)ids=p.page.items.filter(i=>i.groupId===item.groupId).map(i=>i.id);drag.current={};for(const id of ids){const o=p.page.items.find(i=>i.id===id);if(o&&!o.locked&&!o.fixed)drag.current[id]={x:o.x,y:o.y}}const others=p.page.items.filter(i=>!drag.current[i.id]);dragCache.current={nodes:Object.keys(drag.current).map(id=>[id,stage.current?.findOne('#'+id)] as [string,Konva.Node]).filter(([,n])=>!!n),tx:[0,W/2,W,item.x,...others.flatMap(i=>[i.x,i.x+i.w/2,i.x+i.w])],ty:[0,H/2,H,...others.flatMap(i=>[i.y,i.y+i.h/2,i.y+i.h])]}},onDragMove:(e:any)=>{const n=e.target,a=drag.current[item.id];if(!a)return;let nx=n.x(),ny=n.y();if(p.snap){const targetsX=dragCache.current.tx,targetsY=dragCache.current.ty;if(p.grid){nx=Math.round(nx/20)*20;ny=Math.round(ny/20)*20}else{for(const v of targetsX)if(Math.abs(nx-v)<10){nx=v;break}for(const v of targetsY)if(Math.abs(ny-v)<10){ny=v;break}}n.position({x:nx,y:ny})}const dx=nx-a.x,dy=ny-a.y;for(const [id,node] of dragCache.current.nodes){if(id===item.id)continue;const v=drag.current[id];if(v)node.position({x:v.x+dx,y:v.y+dy})}},onDragEnd:()=>{const result:Record<string,Partial<Item>>={};for(const id of Object.keys(drag.current)){const node=stage.current?.findOne('#'+id);if(node)result[id]={x:Math.round(node.x()),y:Math.round(node.y())}}p.onBatch(result);drag.current={}}};
return <Group key={item.id} {...common}><Group x={item.flipX?item.w:0} y={item.flipY?item.h:0} scaleX={item.flipX?-1:1} scaleY={item.flipY?-1:1} listening={!item.locked}>{['text','clock','timer'].includes(item.type)?<Shape fill="#ffffff" width={item.w} height={item.h} sceneFunc={ctx=>drawText((ctx as any)._context,run&&state.effect==='text'?{...item,text:item.text.slice(0,Math.ceil(item.text.length*state.progress))}:item,p.time)} hitFunc={(ctx,shape)=>{ctx.beginPath();ctx.rect(0,0,item.w,item.h);ctx.closePath();ctx.fillStrokeShape(shape)}}/>:item.type==='video'&&(item.src==='hdmirx'||!!item.src?.startsWith('/dev/video'))?<><Rect width={item.w} height={item.h} fill="#11131c"/><Text text="HDMI 입력 (라이브)" width={item.w} height={item.h} align="center" verticalAlign="middle" fill="#7fd1ff" fontSize={Math.min(item.w,item.h)*.08} listening={false}/></>:item.type==='image'||item.type==='video'?<><MediaImage item={item} time={p.time} playing={p.playing} stage={stage}/><Rect width={item.w} height={item.h} fill="#00000000"/></>:item.type==='ellipse'?<Ellipse x={item.w/2} y={item.h/2} radiusX={item.w/2} radiusY={item.h/2} fill={item.fill} stroke={item.stroke} strokeWidth={item.strokeWidth} shadowColor={item.shadow?item.shadowColor:undefined} shadowBlur={item.shadow?item.shadowBlur:0}/>:<Rect width={item.w} height={item.h} fill={item.fill} stroke={item.stroke} strokeWidth={item.strokeWidth} shadowColor={item.shadow?item.shadowColor:undefined} shadowBlur={item.shadow?item.shadowBlur:0}/>}</Group>{fold&&<Shape listening={false} sceneFunc={ctx=>{const c=(ctx as any)._context as CanvasRenderingContext2D;c.save();c.beginPath();c.moveTo(fold!.x,0);c.lineTo(fold!.x-fold!.width,0);c.lineTo(fold!.x,fold!.height);c.closePath();const g=c.createLinearGradient(fold!.x-fold!.width,0,fold!.x,fold!.height);g.addColorStop(0,'#fff');g.addColorStop(.7,'#bbb');g.addColorStop(1,'#333');c.fillStyle=g;c.fill();c.restore()}}/>}</Group>})}</Group>
{p.guide&&!p.preview&&!p.playing&&<><Rect name="guide" x={W*.05} y={H*.05} width={W*.9} height={H*.9} stroke="#ddd" dash={[6,4]} strokeWidth={1/p.scale} listening={false}/><Rect name="guide" x={W/2} width={1/p.scale} height={H} fill="#993e3260" listening={false}/><Rect name="guide" y={H/2} height={1/p.scale} width={W} fill="#993e3260" listening={false}/></>}{box&&<Rect name="guide" x={box.x} y={box.y} width={box.w} height={box.h} fill="#efd94322" stroke="#ffe600" strokeWidth={1/p.scale} listening={false}/>}
<Transformer ref={tr} borderStroke="#ffe600" anchorFill="#ffe600" anchorStroke="#333" anchorSize={8} rotateAnchorOffset={24} anchorCornerRadius={1} borderStrokeWidth={1} anchorStrokeWidth={1} rotateEnabled={!p.selection.some(id=>p.page.items.find(i=>i.id===id)?.fixed)} boundBoxFunc={(old,b)=>b.width<10||b.height<10?old:b} onTransformEnd={()=>{const result:Record<string,Partial<Item>>={};for(const n of tr.current?.nodes()||[]){const o=p.page.items.find(i=>i.id===n.id());if(!o||o.locked||o.fixed)continue;result[o.id]={x:Math.round(n.x()),y:Math.round(n.y()),w:Math.max(10,Math.round(o.w*n.scaleX())),h:Math.max(10,Math.round(o.h*n.scaleY())),rotation:Math.round(n.rotation()),size:Math.max(10,Math.min(1200,Math.round(o.size*n.scaleY())))};n.scaleX(1);n.scaleY(1)}p.onBatch(result)}}/></Layer></Stage>}
