import type Konva from 'konva';
import {Item,Page,W,H,effectState} from './model';
export type Visual={opacity:number;x:number;y:number;scaleX:number;scaleY:number;rotation:number;clip?: (c:Konva.Context)=>void;fold?:{x:number;width:number;height:number}};
export function visual(i:Item,time:number,mode:Page['mode'],duration:number):Visual{const state=effectState(i,time,mode,duration),q=state.progress,f=state.effect,d=i.direction,preset=i.effectPreset;const v:Visual={opacity:1,x:0,y:0,scaleX:1,scaleY:1,rotation:0};if(f==='fade')v.opacity=q;if(f==='blink')v.opacity=Math.floor(state.elapsed*Math.max(1,i.blinkCount)*2/Math.max(1,i.duration))%2?0:1;if(f==='move'){v.x=(d==='left'?-W:d==='right'?W:0)*(1-q);v.y=(d==='up'?-H:d==='down'?H:0)*(1-q);if(preset>=4){v.x=(preset%2?-W:W)*(1-q);v.y=(preset%4<2?-H:H)*(1-q)}}if(f==='scale'){v.scaleX=preset===5?1:q;v.scaleY=preset===4?1:q;v.x=d==='right'?i.w*(1-v.scaleX):d==='left'?0:i.w*(1-v.scaleX)/2;v.y=d==='down'?i.h*(1-v.scaleY):d==='up'?0:i.h*(1-v.scaleY)/2}if(f==='crawl')v.x=(d==='right'?1:-1)*q*(W+i.w)*i.speed;if(f==='roll')v.y=(d==='down'?1:-1)*q*(H+i.h)*i.speed;
if(f==='wipe'||f==='banner'||f==='curl'){v.clip=c=>{c.beginPath();if(preset%8===4)c.rect(i.w*(1-q)/2,0,i.w*q,i.h);else if(preset%8===5)c.rect(0,i.h*(1-q)/2,i.w,i.h*q);else if(preset%8===6){c.moveTo(0,0);c.lineTo(i.w*q*2,0);c.lineTo(0,i.h*q*2)}else if(preset%8===7){c.moveTo(i.w,0);c.lineTo(i.w-i.w*q*2,0);c.lineTo(i.w,i.h*q*2)}else if(d==='up'||d==='down')c.rect(0,d==='up'?i.h*(1-q):0,i.w,i.h*q);else c.rect(d==='left'?i.w*(1-q):0,0,i.w*q,i.h);c.closePath()};if(f==='curl'){v.rotation=i.effectAngle*(1-q);if(q>0&&q<1)v.fold={x:i.w*q,width:Math.min(i.curlRadius*2,i.w*q,i.w*(1-q)),height:Math.min(i.h,i.curlRadius*2)}}if(f==='banner'){v.y=(1-q)*i.h*(d==='up'?-1:1);v.scaleY=Math.max(.01,q);v.rotation=Math.sin(q*Math.PI)*(preset%2?8:-8)}}
if((f==='wipe'||f==='organic')&&i.softness>0&&q<1)v.opacity=Math.min(1,q*4);
if(f==='organic'){v.clip=c=>{c.beginPath();const nx=16,ny=12;for(let a=0;a<nx;a++)for(let b=0;b<ny;b++){const seed=((a*73856093)^(b*19349663)^((preset+1)*83492791))>>>0;const t=(seed%1000)/1000;const k=Math.max(0,Math.min(1,(q-t)*4));if(k>0){const w=i.w/nx,h=i.h/ny;if(preset%3===0)c.rect(a*w,b*h,w*k,h*k);else if(preset%3===1)c.rect(a*w+(1-k)*w/2,b*h,w*k,h);else{c.moveTo(a*w+w/2+w*k,b*h+h/2);c.arc(a*w+w/2,b*h+h/2,Math.hypot(w,h)*k/2,0,Math.PI*2)}}}if(q===1)c.rect(0,0,i.w,i.h);c.closePath()}}
if(f==='tile'){v.clip=c=>{c.beginPath();const nx=Math.min(32,Math.max(1,i.tileX)),ny=Math.min(32,Math.max(1,i.tileY));for(let a=0;a<nx;a++)for(let b=0;b<ny;b++){const offset=preset%3===0?0:preset%3===1?(a+b)/(nx+ny)*.7:(((a*17+b*31)%97)/97)*.7;const k=Math.max(0,Math.min(1,(q-offset)/(1-offset)));c.rect(a*i.w/nx+(1-k)*i.w/nx/2,b*i.h/ny+(1-k)*i.h/ny/2,i.w*k/nx,i.h*k/ny)}c.closePath()}}
return v}
