'use client';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {ExternalLink,Maximize2,Minimize2,GripVertical} from 'lucide-react';
export type PanelId='pages'|'canvas'|'catalog'|'attributes'|'preview'|'colors';
export type Layout={order:PanelId[];floating:PanelId[]};
export const defaultLayout:Layout={order:['pages','canvas','catalog','attributes','preview','colors'],floating:[]};
export function Panel({id,title,children,layout,setLayout,onMessage}:{id:PanelId;title:string;children:React.ReactNode;layout:Layout;setLayout:(l:Layout)=>void;onMessage:(s:string)=>void}){
const [pos,setPos]=useState({x:80,y:100}),[external,setExternal]=useState<HTMLElement|null>(null);const popup=useRef<Window|null>(null),drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);const float=layout.floating.includes(id);const n=layout.order.indexOf(id);const slots=[['1 / 5','1'],['5 / 21','1'],['21 / 25','1'],['1 / 10','2'],['10 / 21','2'],['21 / 25','2']];const placement={gridColumn:slots[n]?.[0],gridRow:slots[n]?.[1]};const dock=()=>{popup.current?.close();popup.current=null;setExternal(null);setLayout({...layout,floating:layout.floating.filter(i=>i!==id)})};
useEffect(()=>()=>popup.current?.close(),[]);
const newWindow=()=>{if(popup.current&&!popup.current.closed){popup.current.focus();return}const w=window.open('','cg-panel-'+id,'width=950,height=700');if(!w){setLayout({...layout,floating:[...new Set([...layout.floating,id])]});onMessage('별도 창이 차단되어 화면 안에 패널을 분리했습니다. 브라우저에서 팝업을 허용하면 다른 모니터로 이동할 수 있습니다.');return}w.document.title=title+' · CG 편집기';w.document.body.innerHTML='<div id="panel-root"></div>';w.document.body.style.margin='0';for(const el of document.querySelectorAll('link[rel="stylesheet"],style'))w.document.head.appendChild(el.cloneNode(true));const r=w.document.getElementById('panel-root')!;r.style.height='100vh';setExternal(r);popup.current=w;w.addEventListener('beforeunload',()=>{setExternal(null);popup.current=null});};
const header=<div className="paneltitle panel-drag" draggable={!float&&!external} onDragStart={e=>e.dataTransfer.setData('application/cg-panel',id)} onPointerDown={e=>{if(!float||external||(e.target as HTMLElement).closest('button'))return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,px:pos.x,py:pos.y}}} onPointerMove={e=>{const d=drag.current;if(d)setPos({x:Math.max(0,d.px+e.clientX-d.x),y:Math.max(0,d.py+e.clientY-d.y)})}} onPointerUp={()=>{drag.current=null}}><span><GripVertical size={13}/>{title}</span><div className="panel-actions"><button title={float||external?'원래 위치로':'화면 안에 분리'} onClick={()=>float||external?dock():setLayout({...layout,floating:[...layout.floating,id]})}>{float||external?<Minimize2 size={13}/>:<Maximize2 size={13}/>}</button><button title="별도 창 · 다른 모니터" onClick={newWindow}><ExternalLink size={13}/></button></div></div>;
const body=<section className={'panel dock-panel '+id+(float?' floating-panel':'')} style={float&&!external?{left:pos.x,top:pos.y,width:id==='canvas'?900:600,height:id==='canvas'?570:350}:external?{height:'100vh',width:'100%',position:'relative'}:undefined}>{header}<div className="panel-content">{children}</div></section>;
if(external)return <><div style={placement} className={'panel-placeholder '+id}><span>{title} · 별도 창</span><button onClick={()=>popup.current?.focus()}>창 보기</button><button onClick={dock}>원위치</button></div>{createPortal(body,external)}</>;
if(float)return <><div style={placement} className={'panel-placeholder '+id}><span>{title} · 분리됨</span><button onClick={dock}>원위치</button></div>{body}</>;
return <div className={'panel-slot '+id} style={placement} onDragOver={e=>{if(e.dataTransfer.types.includes('application/cg-panel'))e.preventDefault()}} onDrop={e=>{const source=e.dataTransfer.getData('application/cg-panel') as PanelId;if(!layout.order.includes(source))return;e.preventDefault();const a=[...layout.order],i=a.indexOf(source),j=a.indexOf(id);[a[i],a[j]]=[a[j],a[i]];setLayout({...layout,order:a})}}>{body}</div>
}
