import assert from 'node:assert/strict';
import {Miniflare} from 'miniflare';
import fs from 'node:fs/promises';
import path from 'node:path';
async function files(dir){const result=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())result.push(...await files(p));else if(/\.m?js$/.test(e.name))result.push({type:'ESModule',path:path.resolve(p)})}return result}
const modules=await files('dist/server');const entry=modules.findIndex(m=>m.path===path.resolve('dist/server/index.js'));modules.unshift(...modules.splice(entry,1));
const mf=new Miniflare({modules,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'cg-test-db'},r2Buckets:{BUCKET:'cg-test-assets'},d1Persist:false,r2Persist:false,cf:false});
try{
const db=await mf.getD1Database('DB');for(const s of (await fs.readFile('drizzle/0000_tired_shocker.sql','utf8')).split('--> statement-breakpoint'))if(s.trim())await db.prepare(s).run();
const headers=(owner='test-a')=>({'oai-authenticated-user-id':owner,'oai-authenticated-user-email':owner+'@example.invalid'});
async function request(route,method='GET',body,owner='test-a',extra={}){const request=new Request('https://cg-test.invalid'+route,{method,headers:{...headers(owner),...extra,...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});return mf.dispatchFetch(request.url,{method,headers:Object.fromEntries(request.headers),body:body?new Uint8Array(await request.arrayBuffer()):undefined})}
let root=await request('/');assert.equal(root.status,200,await root.clone().text());assert.ok((await root.text()).includes('CG'));
let r=await request('/api/projects');assert.equal(r.status,200,await r.clone().text());assert.deepEqual((await r.json()).projects,[]);
const form=new FormData();form.append('file',new Blob([new Uint8Array([137,80,78,71,13,10,26,10])],{type:'image/png'}),'test.png');r=await request('/api/media','POST',form);assert.equal(r.status,200,await r.clone().text());const media=await r.json();r=await request(media.src);assert.equal(r.status,200);assert.equal((await r.arrayBuffer()).byteLength,8);r=await request(media.src,'GET',undefined,'test-a',{Range:'bytes=2-4'});assert.equal(r.status,206);assert.equal(r.headers.get('Content-Range'),'bytes 2-4/8');assert.equal((await r.arrayBuffer()).byteLength,3);r=await request(media.src,'GET',undefined,'test-b');assert.equal(r.status,404);
const project={format:'cg-editor',version:2,name:'保存 확인',pages:[{id:'page',name:'페이지',bg:'transparent',duration:120,mode:'MultiLayer',items:[{id:'item',type:'text',name:'자막',text:'저장하고 다시 열기',x:200,y:300,w:800,h:100,size:80,fill:'#ffffff',start:4,duration:12,effect:'fade'}]}]};r=await request('/api/projects','POST',{project});assert.equal(r.status,200,await r.clone().text());const saved=await r.json();r=await request('/api/projects/'+saved.id);assert.equal(r.status,200,await r.clone().text());const opened=await r.json();assert.equal(opened.project.pages[0].items[0].text,'저장하고 다시 열기');assert.equal(opened.project.pages[0].items[0].start,4);assert.equal(opened.project.pages[0].items[0].duration,12);r=await request('/api/projects/'+saved.id,'GET',undefined,'test-b');assert.equal(r.status,404);r=await request('/api/projects','GET',undefined,'test-b');assert.deepEqual((await r.json()).projects,[]);
r=await request('/api/projects','POST',{project:{...project,name:'수정 저장'},id:saved.id,revision:1});assert.equal(r.status,200);assert.equal((await r.json()).revision,2);r=await request('/api/projects','POST',{project,id:saved.id,revision:1});assert.equal(r.status,409);r=await request('/api/projects/'+saved.id);assert.equal((await r.json()).project.name,'수정 저장');
r=await mf.dispatchFetch('https://cg-test.invalid/api/projects');assert.equal(r.status,401);console.log('Worker API save/reopen, media bytes/range, ownership isolation, version conflicts and auth: passed');
}finally{await mf.dispose()}
